ALTER TABLE inventory_parts 
  ADD COLUMN IF NOT EXISTS year_from VARCHAR(50) NULL AFTER year,
  ADD COLUMN IF NOT EXISTS year_to VARCHAR(50) NULL AFTER year_from,
  ADD COLUMN IF NOT EXISTS is_exact_year_only TINYINT(1) NOT NULL DEFAULT 0 AFTER year_to;
